# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: ^reports/|^test-results/
      - id: end-of-file-fixer
        exclude: ^reports/|^test-results/
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=2000']
      - id: check-ast

  - repo: local
    hooks:
      - id: python-syntax-check
        name: Python Syntax Check
        entry: python -m py_compile
        language: system
        types: [python]
